version: "3.9"
services:
  gaia:
    image: "gaiaapp/gaia"
    ports:
      - "8888:8080"
    environment:
      - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
      - "GAIA_RUNNER_API_PASSWORD=123456"
      - "GAIA_EXTERNAL_URL=http://gaia:8080"
  runner:
    image: "gaiaapp/runner"
    environment:
      - "GAIA_URL=http://gaia:8080"
      - "GAIA_RUNNER_API_PASSWORD=123456"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: "mongo:4.4"
  
  rover:
    image: "im2nguyen/rover"
    ports:
      - "9000:9000"
    volumes:
      - "./:/src"
    command: ["--rm", "-it"]
